version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
python:
  version: 3.8
  install:
  - requirements: .pip-2033.txt
  - method: pip
    path: .
    extra_requirements:
    - doc
