version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
python:
  version: 3.8
  install:
  # https://github.com/takluyver/flit/pull/388
  - method: pip
    path: pip==20.3.3
  - method: pip
    path: .
    extra_requirements:
    - doc
